### PR TITLE
add tax_sources field to lica and taxon services

### PR DESCRIPTION
**Pull request by pmidford**
The code for this was mostly already there, but broken.  Needed for taxonomy browser.

### CODE REVIEW

**Comment by jar398** [comment]
Using a map to represent the list of sources is going to fail when source taxa have been merged.  E.g.

168560	|	168564	|	Rebecca salina	|	species	|	ncbi:561169,silva:L34669,worms:573916,gbif:6540134,gbif:3202282,irmng:10914590,irmng:11820398	|		|		|	

If this is a deep assumption, I guess we can live with it, but if it's not too hard to change I think it would be worthwhile to.

**Comment by pmidford** [comment]
Could just leave it as a string, and let the browser parse it out, or use a list.  Either is easy.

**Comment by jar398** [comment]
Maybe a list of strings?  The syntax of sourceids is that of 'curieoruri', so a simple break at the colon is not necessarily the right thing. Currently only one example of a URL in the source list, but I expect a lot of examples in the future.

5341349	|	770315	|	Homo sapiens sapiens	|	subspecies	|	https://en.wikipedia.org/wiki/Homo_sapiens_sapiens	|		|	hidden,infraspecific	|

**Comment by pmidford** [comment]
That makes sense.  Will update.

**Comment by jar398** [comment]
here's the reference. I should put this in the taxonomy format documentation.
http://www.w3.org/TR/rdfa-core/#s_curieprocessing

**Pull request merged**
